mod academics_page;
mod additional_page;
mod athletics_page;
mod demographics_page;
mod eligibility_page;
mod extracurriculars_page;
mod family_info_page;
mod form_setup;
mod home_page;
mod shell;
mod test_display;
mod university_page;
mod work_experience_page;

pub use academics_page::*;
pub use additional_page::*;
pub use athletics_page::*;
pub use demographics_page::*;
pub use eligibility_page::*;
pub use extracurriculars_page::*;
pub use family_info_page::*;
pub use home_page::*;
pub use shell::*;
pub use test_display::*;
pub use university_page::*;
pub use work_experience_page::*;
